plugins {
	id "io.spring.nullability"
	id "java"
}

nullability {
	jspecifyExperimental = true
}

dependencies {
	compileOnly("org.jspecify:jspecify:1.0.0")

	testCompileOnly("org.jspecify:jspecify:1.0.0")
}

tasks.register("checkCompileJava") {
	doFirst {
		println compileJava.options.extensions.errorprone
	}
}
