name: Sync to Maven Central
description: Syncs a release to Maven Central and waits for it to be available for use
inputs:
  central-token-password:
    description: 'Password for authentication with central.sonatype.com'
    required: true
  central-token-username:
    description: 'Username for authentication with central.sonatype.com'
    required: true
  jfrog-cli-config-token:
    description: 'Config token for the JFrog CLI'
    required: true
  nullability-plugin-version:
    description: 'The version of Compatibility Test Plugin that is being synced to Central'
    required: true
runs:
  using: composite
  steps:
    - name: Set Up JFrog CLI
      uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
      env:
        JF_ENV_SPRING: ${{ inputs.jfrog-cli-config-token }}
    - name: Download Release Artifacts
      shell: bash
      run: jf rt download --spec ${{ format('{0}/artifacts.spec', github.action_path) }} --spec-vars 'buildName=${{ format('nullability-plugin-{0}', inputs.nullability-plugin-version) }};buildNumber=${{ github.run_number }}'
    - name: Sync
      uses: spring-io/central-publish-action@0cdd90d12e6876341e82860d951e1bcddc1e51b6 # v0.2.0
      with:
        token: ${{ inputs.central-token-password }}
        token-name: ${{ inputs.central-token-username }}
    - name: Await
      shell: bash
      run: |
        url=${{ format('https://repo.maven.apache.org/maven2/io/spring/gradle/nullability/nullability-plugin/{0}/nullability-plugin-{0}.jar', inputs.nullability-plugin-version) }}
        echo "Waiting for $url"
        until curl --fail --head --silent $url > /dev/null
        do
          echo "."
          sleep 60
        done
        echo "$url is available"
